nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: warjiang/cloudflaretunnel-operator
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: ""

leaderElection:
  enabled: true

metrics:
  enabled: true
  service:
    enabled: true
    port: 8443

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

nodeSelector: {}
tolerations: []
affinity: {}

extraArgs: []

connectorDefaults:
  image: cloudflare/cloudflared:2026.3.0
  replicas: 1
