apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
type: Opaque
stringData:
  api-token: "<YOUR_CLOUDFLARE_API_TOKEN>"
  account-id: "<YOUR_CLOUDFLARE_ACCOUNT_ID>"
---
apiVersion: cloudflaretunnel.spotty.com.cn/v1alpha1
kind: CloudflareTunnel
metadata:
  labels:
    app.kubernetes.io/name: cloudflaretunnel-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflaretunnel-sample
spec:
  name: createbycr
  credentialsRef:
    name: cloudflare-credentials
  tokenSecretRef:
    name: cloudflaretunnel-sample-token
