apiVersion: cloudflaretunnel.spotty.com.cn/v1alpha1
kind: CloudflareTunnel
metadata:
  labels:
    app.kubernetes.io/name: cloudflaretunnel-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflaretunnel-sample
spec:
  # TODO(user): Add fields here
