apiVersion: cloudflaretunnel.spotty.com.cn/v1alpha1
kind: CloudflareTunnel
metadata:
  labels:
    app.kubernetes.io/name: cloudflaretunnel-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflaretunnel-sample
spec:
  name: my-first-tunnel
  credentialsRef:
    name: cloudflare-credentials
  tokenSecretRef:
    name: cloudflaretunnel-sample-token
