{{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflaretunnel-operator.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflaretunnel-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: https
  selector:
    {{- include "cloudflaretunnel-operator.selectorLabels" . | nindent 4 }}
{{- end }}
